<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */
 
 add_action( 'genesis_before_content', 'feature_image' );
 function feature_image() {
 	if ( has_post_thumbnail() ) {
 		the_post_thumbnail();
 	}
 }

// This file handles pages, but only exists for the sake of child theme forward compatibility.
genesis();
